### ISSUE TITLE
PR Template Modify who can merge into main branch

### ISSUE THREAD

**Issue by Acha0203** [sinProject-Inc/sinpro-template#14]
# Tasks

- [x] Add "On Slack, mention the PR submitter and a project admin, write which PR you have reviewed, and ask the project admin to review and merge the PR" and "If you are a project admin, merge the PR" to "After Reviewing" section on pull_request_template.md

Estimated Time: 10 min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [ ] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
